/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        zeno: {
          blue: "#0057FF",
          "blue-light": "#EAF6FF",
          green: "#C7FF4A",
          dark: "#0A1712",
          intro: "#1B2812",
          background: "#F4FAFF",
          "auth-background": "#FAFEF0",
          sky: "#EAF6FF",
          surface: "#FFFFFF",
          "surface-soft": "#F1F7FF",
          border: "#D9E4FF",
          "text-primary": "#071706",
          "text-secondary": "#6B7280",
          "text-subtitle": "#535353",
          "link-blue": "#1C64E8",
          success: "#22C55E",
          warning: "#F59E0B",
          error: "#EF4444",
        },
      },
      fontFamily: {
        sans: ["SFProDisplay-Regular", "system-ui", "sans-serif"],
        body: ["SFProDisplay-Regular", "system-ui", "sans-serif"],
        semibold: ["SFProDisplay-Semibold", "system-ui", "sans-serif"],
        bold: ["SFProDisplay-Bold", "system-ui", "sans-serif"],
        heavy: ["SFProDisplay-Heavy", "system-ui", "sans-serif"],
        condensed: ["ZalandoCondensed-Regular", "system-ui", "sans-serif"],
      },
      fontSize: {
        display: ["36px", { lineHeight: "43.2px", letterSpacing: "-0.02em" }],
        h1: ["32px", { lineHeight: "38.4px" }],
        h2: ["24px", { lineHeight: "28.8px" }],
        h3: ["20px", { lineHeight: "24px" }],
        body: ["16px", { lineHeight: "22.4px" }],
        "body-sm": ["14px", { lineHeight: "19.6px" }],
        caption: ["12px", { lineHeight: "16.8px" }],
      },
      borderRadius: {
        sm: "12px",
        md: "20px",
        lg: "28px",
        xl: "32px",
        pill: "9999px",
      },
      boxShadow: {
        low: "0 2px 4px rgba(0, 0, 0, 0.08)",
        medium: "0 4px 8px rgba(0, 0, 0, 0.1)",
        high: "0 8px 16px rgba(0, 0, 0, 0.15)",
        hero: "0 20px 40px rgba(10, 23, 18, 0.08)",
        card: "0 12px 28px rgba(10, 23, 18, 0.08)",
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        8: "32px",
        10: "40px",
        12: "48px",
        14: "56px",
        16: "64px",
        18: "72px",
        20: "80px",
      },
    },
  },
  plugins: [],
};